name: "[Develop] Unity Actions 😎"

on: 
  workflow_dispatch:

jobs:
  androidBuild:
    uses: ./.github/workflows/gameci-androidbuild.yml
    with:
      environment: 'Development'
      unity-custom-image: 'unityci/editor:windows-6000.0.11f1-android-3.1.0'
      android-api-level: 'AndroidApiLevel34'
      playstore-lane: 'android internal'
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
      ANDROID_KEYALIAS_NAME: ${{ secrets.ANDROID_KEYALIAS_NAME }}
      ANDROID_KEYALIAS_PASS: ${{ secrets.ANDROID_KEYALIAS_PASS }}
  
      # Pull To release branch
  pullToRelease:
    name: Create pull request to Release
    needs: androidBuild
    uses: ./.github/workflows/autopullrequest.yml
    with:
      branch-name: 'release'