name: "[Feature] Unity Actions 😎"

on: 
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - 'config/**' 
      - 'infra/**'

jobs:
  pullToDevelop:
    name: Create pull request to Develop
    uses: ./.github/workflows/autopullrequest.yml
    with:
      branch-name: 'develop'
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
